# Generated by Django 3.2.7 on 2022-03-08 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220308_1047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cat_title',
            new_name='title',
        ),
    ]
